-- Create the work_attendance table (single-user version)
create table if not exists public.work_attendance (
    id bigint generated by default as identity primary key,
    date date not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,

    -- Each date can only be checked in once
    constraint work_attendance_date_key unique (date)
);

-- Add comments to the table and columns
comment on table public.work_attendance is '''Stores work attendance records (for a single user).''';
comment on column public.work_attendance.id is '''Unique identifier for each attendance record.''';
comment on column public.work_attendance.date is '''The specific date of the attendance.''';
comment on column public.work_attendance.created_at is '''Timestamp when the record was created.''';